// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhWtjfKTWaXz6CEpAql79pYb-Ka-Zonwg',
    appId: '1:908952951822:web:ac0d6cebba219ad44d305f',
    messagingSenderId: '908952951822',
    projectId: 'flutter-todolist-05-05-2006',
    authDomain: 'flutter-todolist-05-05-2006.firebaseapp.com',
    storageBucket: 'flutter-todolist-05-05-2006.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw9iJYAJr4MXr7ae5PyL2TokzOXfwXX-E',
    appId: '1:908952951822:android:a3fc10469774d3a94d305f',
    messagingSenderId: '908952951822',
    projectId: 'flutter-todolist-05-05-2006',
    storageBucket: 'flutter-todolist-05-05-2006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDgwbCwIg81O_SwYm6YD-uJOMqeGE6Yk',
    appId: '1:908952951822:ios:d83d45f031ee0f6e4d305f',
    messagingSenderId: '908952951822',
    projectId: 'flutter-todolist-05-05-2006',
    storageBucket: 'flutter-todolist-05-05-2006.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpDgwbCwIg81O_SwYm6YD-uJOMqeGE6Yk',
    appId: '1:908952951822:ios:d83d45f031ee0f6e4d305f',
    messagingSenderId: '908952951822',
    projectId: 'flutter-todolist-05-05-2006',
    storageBucket: 'flutter-todolist-05-05-2006.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhWtjfKTWaXz6CEpAql79pYb-Ka-Zonwg',
    appId: '1:908952951822:web:beedcb3c101cc6894d305f',
    messagingSenderId: '908952951822',
    projectId: 'flutter-todolist-05-05-2006',
    authDomain: 'flutter-todolist-05-05-2006.firebaseapp.com',
    storageBucket: 'flutter-todolist-05-05-2006.appspot.com',
  );

}